<?php

namespace MahdiAbderraouf\FacturX\Enums;

/**
 * List of Factur-X possible invoice type codes.
 *
 * @see https://service.unece.org/trade/untdid/d22b/tred/tred1001.htm
 */
enum InvoiceTypeCode: string
{
    /** The most common */
    case COMMERCIAL_INVOICE = '380';
    case CREDIT_NOTE = '381';
    case PREPAYMENT_INVOICE = '386';
    case CORRECTED_INVOICE = '384';
    case SELF_BILLED_INVOICE = '389';
    case SELF_BILLED_CREDIT_NOTE = '261';
    case CONSOLIDATED_CREDIT_NOTE_GOODS_SERVICES = '262';
    case INVOICE_INFORMATION_ACCOUNTING = '751';

    /** Others */
    case REQUEST_FOR_PAYMENT = '71';
    case DEBIT_NOTE_GOODS_SERVICES = '80';
    case CREDIT_NOTE_GOODS_SERVICES = '81';
    case METERED_SERVICES_INVOICE = '82';
    case CREDIT_NOTE_FINANCIAL_ADJUSTMENTS = '83';
    case DEBIT_NOTE_FINANCIAL_ADJUSTMENTS = '84';
    case TAX_NOTIFICATION = '102';
    case INVOICING_DATA_SHEET = '130';
    case DIRECT_PAYMENT_VALUATION = '202';
    case PROVISIONAL_PAYMENT_VALUATION = '203';
    case PAYMENT_VALUATION = '204';
    case INTERIM_APPLICATION_FOR_PAYMENT = '211';
    case FINAL_PAYMENT_REQUEST_COMPLETION_WORK = '218';
    case PAYMENT_REQUEST_COMPLETED_UNITS = '219';
    case PRICE_VARIATION_INVOICE = '295';
    case CREDIT_NOTE_PRICE_VARIATION = '296';
    case DELCREDERE_CREDIT_NOTE = '308';
    case PROFORMA_INVOICE = '325';
    case PARTIAL_INVOICE = '326';
    case COMMERCIAL_INVOICE_PACKING_LIST = '331';
    case COMMISSION_NOTE = '382';
    case DEBIT_NOTE = '383';
    case CONSOLIDATED_INVOICE = '385';
    case HIRE_INVOICE = '387';
    case TAX_INVOICE = '388';
    case DELCREDERE_INVOICE = '390';
    case FACTORED_INVOICE = '393';
    case LEASE_INVOICE = '394';
    case CONSIGNMENT_INVOICE = '395';
    case FACTORED_CREDIT_NOTE = '396';
    case OCR_PAYMENT_CREDIT_NOTE = '420';
    case DEBIT_ADVICE = '456';
    case REVERSAL_OF_DEBIT = '457';
    case REVERSAL_OF_CREDIT = '458';
    case SELF_BILLED_DEBIT_NOTE = '527';
    case FORWARDERS_CREDIT_NOTE = '532';
    case FORWARDERS_INVOICE_DISCREPANCY_REPORT = '553';
    case INSURERS_INVOICE = '575';
    case FORWARDERS_INVOICE = '623';
    case PORT_CHARGES_DOCUMENTS = '633';
    case FREIGHT_INVOICE = '780';
    case CLAIM_NOTIFICATION = '817';
    case CONSULAR_INVOICE = '870';
    case PARTIAL_CONSTRUCTION_INVOICE = '875';
    case PARTIAL_FINAL_CONSTRUCTION_INVOICE = '876';
    case FINAL_CONSTRUCTION_INVOICE = '877';
    case CUSTOMS_INVOICE = '935';
}
