version: "3.8"

services:
  facturx:
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
